package handlers

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"
)

// llmMatchResult holds candidates found via LLM-powered fuzzy matching.
type llmMatchResult struct {
	Candidates []llmCandidate
}

type llmCandidate struct {
	OLID     string
	Title    string
	CoverURL string
	Authors  []string
	Year     *int
}

// llmFuzzyMatch generates title/author permutations using an LLM, then searches
// Open Library with each permutation to find candidate matches. Called as a last
// resort when all standard lookup methods fail.
//
// Returns up to 5 candidates for user confirmation. Returns nil if the LLM API
// key is not configured or no candidates are found.
func llmFuzzyMatch(ol *cachedOLClient, title, author string) *llmMatchResult {
	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		return nil
	}

	permutations := generatePermutations(apiKey, title, author)
	if len(permutations) == 0 {
		return nil
	}

	// Deduplicate candidates by OL work ID
	seen := map[string]bool{}
	var candidates []llmCandidate

	for _, perm := range permutations {
		if len(candidates) >= 5 {
			break
		}

		q := "title=" + url.QueryEscape(perm.Title)
		if perm.Author != "" {
			q += "&author=" + url.QueryEscape(perm.Author)
		}
		data, err := ol.get(fmt.Sprintf("/search.json?%s&fields=key,title,author_name,first_publish_year,cover_i&limit=3", q))
		if err != nil {
			continue
		}
		docs, ok := data["docs"].([]any)
		if !ok {
			continue
		}
		for _, d := range docs {
			if len(candidates) >= 5 {
				break
			}
			doc, ok := d.(map[string]any)
			if !ok {
				continue
			}
			key, ok := doc["key"].(string)
			if !ok {
				continue
			}
			olID := strings.TrimPrefix(key, "/works/")
			if seen[olID] {
				continue
			}
			seen[olID] = true

			c := llmCandidate{OLID: olID}
			if t, ok := doc["title"].(string); ok {
				c.Title = t
			}
			if coverI, ok := doc["cover_i"].(float64); ok && coverI > 0 {
				c.CoverURL = fmt.Sprintf("https://covers.openlibrary.org/b/id/%.0f-M.jpg", coverI)
			}
			if authorNames, ok := doc["author_name"].([]any); ok {
				for _, a := range authorNames {
					if name, ok := a.(string); ok {
						c.Authors = append(c.Authors, name)
					}
				}
			}
			if y, ok := doc["first_publish_year"].(float64); ok {
				yr := int(y)
				c.Year = &yr
			}
			candidates = append(candidates, c)
		}
	}

	if len(candidates) == 0 {
		return nil
	}
	return &llmMatchResult{Candidates: candidates}
}

// permutation is a title/author pair generated by the LLM.
type permutation struct {
	Title  string `json:"title"`
	Author string `json:"author"`
}

// generatePermutations calls the Anthropic API to generate alternate
// title/author search queries for a book that failed standard lookups.
func generatePermutations(apiKey, title, author string) []permutation {
	prompt := fmt.Sprintf(`A book import failed to find a match in Open Library for:
Title: %q
Author: %q

Generate 5-8 alternative search queries that might find this book. Consider:
- The title may have series info, subtitles, or format tags mixed in
- The author name may be misspelled, reversed (Last, First), or concatenated
- The title may be in a different language or transliterated
- The book may be known by an alternate/shortened title
- Common OCR or data entry errors in the title or author

Return a JSON array of objects with "title" and "author" fields. Each should be a plausible search query. Keep author empty string if uncertain. Only return the JSON array, no other text.`, title, author)

	reqBody := map[string]any{
		"model":      "claude-haiku-4-5-20251001",
		"max_tokens": 1024,
		"messages": []map[string]any{
			{"role": "user", "content": prompt},
		},
	}
	bodyBytes, err := json.Marshal(reqBody)
	if err != nil {
		return nil
	}

	req, err := http.NewRequest("POST", "https://api.anthropic.com/v1/messages", bytes.NewReader(bodyBytes))
	if err != nil {
		return nil
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", apiKey)
	req.Header.Set("anthropic-version", "2023-06-01")

	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil
	}

	var result struct {
		Content []struct {
			Type string `json:"type"`
			Text string `json:"text"`
		} `json:"content"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil
	}

	// Extract text from the first text content block
	var text string
	for _, c := range result.Content {
		if c.Type == "text" {
			text = c.Text
			break
		}
	}
	if text == "" {
		return nil
	}

	// Parse the JSON array from the response — may be wrapped in markdown code fences
	text = strings.TrimSpace(text)
	if start := strings.Index(text, "["); start >= 0 {
		if end := strings.LastIndex(text, "]"); end > start {
			text = text[start : end+1]
		}
	}

	var perms []permutation
	if err := json.Unmarshal([]byte(text), &perms); err != nil {
		return nil
	}

	// Filter out empty or duplicate permutations
	seen := map[string]bool{}
	var filtered []permutation
	for _, p := range perms {
		p.Title = strings.TrimSpace(p.Title)
		p.Author = strings.TrimSpace(p.Author)
		if p.Title == "" {
			continue
		}
		key := strings.ToLower(p.Title) + "|" + strings.ToLower(p.Author)
		if seen[key] {
			continue
		}
		seen[key] = true
		filtered = append(filtered, p)
	}

	return filtered
}
